### PR TITLE
Fix typo in recipient

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Found this typo while using playgrounds. Updated text from `recepient` to `recipient`. 

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cwperks** [comment]
@riysaxen-amzn @AWSHurneyt Can one of you review this PR as well?

**Review by yuye-aws — APPROVED** [review]
Looks good to me

**Comment by cwperks** [comment]
I'll create a manual backport

**Comment by cwperks** [comment]
Created manual backport: https://github.com/opensearch-project/dashboards-notifications/pull/289

**Pull request merged**
