### PR TITLE
[navigation]feat: change parent item name

### PR DESCRIPTION
**Pull request by SuZhou-Joe**
### Description
image

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by yuye-aws — APPROVED** [review]
Looks good to me

**Comment by yuye-aws** [comment]
Should this PR fix https://github.com/opensearch-project/dashboards-notifications/actions/runs/10364397883/job/28689607232?pr=234?

**Comment by SuZhou-Joe** [comment]
I do not think so, the failure seems irrelevant to the code changes.

**Review by yuye-aws — APPROVED** [review]
Looks good to me.

**Review by AWSHurneyt — APPROVED** [review]

**Pull request merged**
