### PR TITLE
Replaced wrongly formatted mock Slack URLs with properly formatted mock Slack URLs

### PR DESCRIPTION
**Pull request by Noir01**
Integrates with [#814](https://github.com/opensearch-project/notifications/pull/814) in the backend notifications repo

### Description
Replaces mock Slack URLs (which wouldn't pass validation tests) with mock Slack URLs (which will pass validation tests)

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Noir01** [comment]
I don't understand why these tests are failing.

**Comment by Hailong-am** [comment]
> I don't understand why these tests are failing.

will fix the failing by https://github.com/opensearch-project/dashboards-notifications/pull/140

**Comment by Noir01** [comment]
> > I don't understand why these tests are failing.
> 
> will fix the failing by #140

Got it.

**Comment by Noir01** [comment]
How can I trigger the checks again? I think they might've been failing cause the tests in main weren't updated. Now that [#814](https://github.com/opensearch-project/notifications/pull/814) has been merged, I think the tests will pass.

**Comment by yuye-aws** [comment]
> How can I trigger the checks again? I think they might've been failing cause the tests in main weren't updated. Now that [#814](https://github.com/opensearch-project/notifications/pull/814) has been merged, I think the tests will pass.

Rerunning now

**Comment by Hailong-am** [comment]
> How can I trigger the checks again? I think they might've been failing cause the tests in main weren't updated. Now that [#814](https://github.com/opensearch-project/notifications/pull/814) has been merged, I think the tests will pass.

@Noir01  You need to run `yarn test:jest -u` to update snapshot of unit tests.

**Comment by Noir01** [comment]
Sorry, I don't understand the error messages again. I'm not very familiar with Cypress, so I'm not able to debug either.

**Comment by SuZhou-Joe** [comment]
> Sorry, I don't understand the error messages again. I'm not very familiar with Cypress, so I'm not able to debug either.

Should be a flaky test, I reran it to see the result.

**Review by Hailong-am — APPROVED** [review]

**Review by SuZhou-Joe — APPROVED** [review]

**Pull request merged**
